name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.2
  - anaconda-auth=0.8.6
  - anaconda-cli-base=0.5.2
  - annotated-types=0.6.0
  - archspec=0.2.3
  - boltons=25.0.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.15
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.2.1
  - colorama=0.4.6
  - conda=25.7.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=45.0.5
  - dbus=1.16.2
  - distro=1.9.0
  - expat=2.7.1
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jeepney=0.7.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.6.0
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.14.1
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - menuinst=2.3.1
  - more-itertools=10.3.0
  - ncurses=6.5
  - nlohmann_json=3.11.2
  - openssl=3.0.17
  - packaging=25.0
  - pcre2=10.42
  - pip=25.1
  - pkce=1.0.3
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pthread-stubs=0.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dotenv=1.1.0
  - python_abi=3.13
  - readchar=4.0.5
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - rich=13.9.4
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - secretstorage=3.3.1
  - semver=3.0.2
  - setuptools=78.1.1
  - shellingham=1.5.0
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.60.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - numpy==2.3.4
      - pillow==12.0.0
      - pycno==0.3.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - six==1.17.0
prefix: /home/jhubadmin/miniconda3
