name: TDT_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - acvl-utils==0.2.5
      - argparse==1.4.0
      - awkward==2.8.9
      - awkward-cpp==50
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - blosc2==3.10.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - connected-components-3d==3.26.0
      - contourpy==1.3.3
      - cramjam==2.11.0
      - cycler==0.12.1
      - dataclasses==0.6
      - dicom2nifti==2.6.2
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - fft-conv-pytorch==1.2.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - future==1.0.0
      - graphviz==0.21
      - h5py==3.15.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.11
      - imagecodecs==2025.8.2
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json-minify==0.3.0
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - libroadrunner==2.8.0
      - linecache2==1.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - msgpack==1.1.2
      - ndindex==1.10.0
      - networkx==3.5
      - nibabel==5.3.2
      - nnunetv2==2.6.2
      - numexpr==2.14.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pillow==12.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydicom==3.0.1
      - pyparsing==3.2.5
      - python-gdcm==3.2.2
      - python-libsbml==5.20.5
      - pytomography==3.4.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rt-utils==1.2.7
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - simpleitk==2.5.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.20
      - torch==2.9.0
      - torchrbf==1.0.0
      - torchvision==0.24.0
      - totalsegmentator==2.11.0
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.5.0
      - tzdata==2025.2
      - unittest2==1.1.0
      - uproot==5.6.6
      - urllib3==2.5.0
      - xvfbwrapper==0.2.14
      - xxhash==3.6.0
      - yacs==0.1.8
